### ISSUE TITLE
Ein Paar Rote zeilen...

### ISSUE THREAD

**Issue by gigi2006** [MysticFoxDE/WINDOWS-OPTIMIZATIONS#1]
``Hey, danke erst mal für das Skript.
Zwar schreibst du das ein paar rote Zeilen in Ordnung sind, aber bei mir sind es nur rote Zeilen.

Als Administrator ausgeführt :)

`PS C:\Users\hierstehteinordnername\Downloads> .\W10ANDW11-NETWORK-TCP-DESUBOPTIMIZATION.ps1
In C:\Users\hierstehteinordnername\Downloads\W10ANDW11-NETWORK-TCP-DESUBOPTIMIZATION.ps1:210 Zeichen:162
+ ... t="true" class="Header-link js-details-target btn-link">    <svg aria ...
+                                                                 ~
Der Operator "<" ist für zukünftige Versionen reserviert.
In C:\Users\hierstehteinordnername\Downloads\W10ANDW11-NETWORK-TCP-DESUBOPTIMIZATION.ps1:213 Zeichen:14
+ </button>    </div>
+              ~
Der Operator "<" ist für zukünftige Versionen reserviert.
In C:\Users\hierstehteinordnername\Downloads\W10ANDW11-NETWORK-TCP-DESUBOPTIMIZATION.ps1:456 Zeichen:31
+         data-analytics-event="{&quot;category&quot;:&quot;Header&quot ...
+                               ~
Unerwartetes Token "{" in Ausdruck oder Anweisung.
In C:\Users\hierstehteinordnername\Downloads\W10ANDW11-NETWORK-TCP-DESUBOPTIMIZATION.ps1:456 Zeichen:46
+         data-analytics-event="{&quot;category&quot;:&quot;Header&quot ...
+                                              ~
Das kaufmännische Und-Zeichen (&) ist nicht zulässig. Der &-Operator ist für eine zukünftige Verwendung reserviert.
Verwenden Sie das kaufmännische Und-Zeichen in doppelten Anführungszeichen ("&"), um es als Teil einer Zeichenfolge zu
übergeben.
In C:\Users\hierstehteinordnername\Downloads\W10ANDW11-NETWORK-TCP-DESUBOPTIMIZATION.ps1:456 Zeichen:53
+         data-analytics-event="{&quot;category&quot;:&quot;Header&quot ...
+                                                     ~
Das kaufmännische Und-Zeichen (&) ist nicht zulässig. Der &-Operator ist für eine zukünftige Verwendung reserviert.
Verwenden Sie das kaufmännische Und-Zeichen in doppelten Anführungszeichen ("&"), um es als Teil einer Zeichenfolge zu
übergeben.
In C:\Users\hierstehteinordnername\Downloads\W10ANDW11-NETWORK-TCP-DESUBOPTIMIZATION.ps1:456 Zeichen:65
+ ...     data-analytics-event="{&quot;category&quot;:&quot;Header&quot;,&q ...
+                                                                 ~
Das kaufmännische Und-Zeichen (&) ist nicht zulässig. Der &-Operator ist für eine zukünftige Verwendung reserviert.
Verwenden Sie das kaufmännische Und-Zeichen in doppelten Anführungszeichen ("&"), um es als Teil einer Zeichenfolge zu
übergeben.
In C:\Users\hierstehteinordnername\Downloads\W10ANDW11-NETWORK-TCP-DESUBOPTIMIZATION.ps1:456 Zeichen:72
+ ... ta-analytics-event="{&quot;category&quot;:&quot;Header&quot;,&quot;ac ...
+                                                                  ~
Ausdruck fehlt nach dem unären Operator ",".
In C:\Users\hierstehteinordnername\Downloads\W10ANDW11-NETWORK-TCP-DESUBOPTIMIZATION.ps1:456 Zeichen:72
+ ... a-analytics-event="{&quot;category&quot;:&quot;Header&quot;,&quot;act ...
+                                                                 ~
Unerwartetes Token "&" in Ausdruck oder Anweisung.
In C:\Users\hierstehteinordnername\Downloads\W10ANDW11-NETWORK-TCP-DESUBOPTIMIZATION.ps1:456 Zeichen:84
+ ... event="{&quot;category&quot;:&quot;Header&quot;,&quot;action&quot;:&q ...
+                                                                 ~
Das kaufmännische Und-Zeichen (&) ist nicht zulässig. Der &-Operator ist für eine zukünftige Verwendung reserviert.
Verwenden Sie das kaufmännische Und-Zeichen in doppelten Anführungszeichen ("&"), um es als Teil einer Zeichenfolge zu
übergeben.
In C:\Users\hierstehteinordnername\Downloads\W10ANDW11-NETWORK-TCP-DESUBOPTIMIZATION.ps1:456 Zeichen:91
+ ... {&quot;category&quot;:&quot;Header&quot;,&quot;action&quot;:&quot;sig ...
+                                                                 ~
Das kaufmännische Und-Zeichen (&) ist nicht zulässig. Der &-Operator ist für eine zukünftige Verwendung reserviert.
Verwenden Sie das kaufmännische Und-Zeichen in doppelten Anführungszeichen ("&"), um es als Teil einer Zeichenfolge zu
übergeben.
Es wurden nicht alle Analysefehler berichtet. Korrigieren Sie die berichteten Fehler, und versuchen Sie es erneut.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : RedirectionNotSupported`

**Comment by gigi2006** [comment]
Hab mal die PowerShell aktualisiert, war nämlich noch älter. Jetzt bekomme ich nur einen Fehler:

![image](https://user-images.githubusercontent.com/32102113/215414243-f3d843b9-ae07-4b9e-b3ab-63113d44ad2d.png)

**Comment by MysticFoxDE** [comment]
Hi gigi2006,
zum Glück habe ich deinen letzten Post gerade entdeckt.
Ich habe im aktuellen Quellcode mir gerade schon angefangen den Wolf abzusuchen, woher die von dir beschriebenen Fehler kommen könnten. 🙃
Was den letzten Fehler angeht, was steht den bei dir in der Registry unter dem folgenden Key
"HKLM:\SYSTEM\CurrentControlSet\Control\Nsi\{eb004a03-9b1a-11d4-9123-0050047759bc}\27\06000000"

Gruss Alex

**Comment by gigi2006** [comment]
Das ist leider leer

![image](https://user-images.githubusercontent.com/32102113/215421576-ffb114ef-5661-4aea-b172-b4e3f7ce9861.png)

Im Übrigen habe ich das gleiche Problem wie der Kollege auf Administrator Forum
also das nichts erscheint bei der Eingabe.

![image](https://user-images.githubusercontent.com/32102113/215421809-9932825d-2797-4fbb-b081-c4a3a6768fc1.png)

**Comment by MysticFoxDE** [comment]
Hi gigi2006,
😯 ... OK und warum läuft das Skript in die Zeile 210, es müsste gemäss Zeile 196, eigentlich zu Zeile 222 springen. 🤔
Gruss Alex

**Comment by MysticFoxDE** [comment]
Hi gigi2006,
zu der leeren Ausgabe von Get-Netadapter-RSS. 
Das bedeutet nur, das in deinem Rechner keine NIC's installiert sind, die RSS unterstützen.

Gruss Alex

**Comment by gigi2006** [comment]
> Hi gigi2006, 😯 ... OK und warum läuft das Skript in die Zeile 210, es müsste gemäss Zeile 196, eigentlich zu Zeile 222 springen. 🤔 Gruss Alex

kann ich dir nicht sagen, dachte du bist mein Mann :)

**Comment by MysticFoxDE** [comment]
Hi gigi2006,
kannst du mal testen ob du den Key von Hand setzen kannst, danke. 
Dieser müsste so aussehen.
![NSI-REG-KEY](https://user-images.githubusercontent.com/123583045/215434623-c31b1175-5ab4-4ab1-905b-581733107e20.jpg)

Gruss Alex

**Comment by gigi2006** [comment]
Habe ich gemacht, leider kommt der gleiche Fehler
(muss dazu sagen, dass ich gerade aber noch nicht neu starten konnte, falls das erforderlich sein sollte)

![image](https://user-images.githubusercontent.com/32102113/215436699-343f996f-c52e-4e0a-9e1c-2ad53f1598be.png)

**Comment by gigi2006** [comment]
Aber schau mal, wenn ich den im Editor öffne, meckert er auch schon, evtl. ein Tippfehler oder er erwartet dort was anderes?

![image](https://user-images.githubusercontent.com/32102113/215437404-c75dfa4f-52f8-42f5-ac0c-06ccec430001.png)

**Comment by gigi2006** [comment]
Jetzt habe ich mal die Leerzeichen dort entfernt und jetzt habe ich das hier:

![image](https://user-images.githubusercontent.com/32102113/215439373-f0a0dcc2-9807-46de-baa3-ea00e454a82b.png)

**Comment by MysticFoxDE** [comment]
Hi gigi2006,
😯 ... woher kommt bei dir dieser Code in den Zeilen 204 bis 222 und 450 bis 473?
Meiner lokal und der bei Github sieht an diesen Stellen etwas anders aus.

![204 bis 222](https://user-images.githubusercontent.com/123583045/215444910-35729efc-5b35-439e-8896-10190d5078dc.jpg)
![450 bis 473](https://user-images.githubusercontent.com/123583045/215444928-7380cc1b-74f6-4e09-a509-37fe69f6e0a2.jpg)

??

Gruss Alex

**Comment by gigi2006** [comment]
Alex das ist mir jetzt etwas peinlich.
Ich hab kA wie ich das gemacht hab, aber ich hab auf dein Script speichern unter gedrückt und er hat mir den HTML Code runtergeladen.

Ich dachte mir auch wieso mein Nickname im Code steht. Dachte erst du hast mich da einkommentiert um zu wissen was du geändert hast. Danach hab ich gemerkt die originale Datei ist 32kb und meine war 499kb.



Sorry sorry echt für die ganze Zeitverschwendung.


Danke dir für deine Hilfe echt.

**Comment by MysticFoxDE** [comment]
Hi gigi2006,
mach dir keinen Kopf, ich habe auch schon mehr als genug Murks gebaut. 🤪
So lernt man eben.

Gruss Alex
