### ISSUE TITLE
How do I revert back the changes?

### ISSUE THREAD

**Issue by OmerrGithubb** [MysticFoxDE/WINDOWS-OPTIMIZATIONS#19]
How do I revert back the changes?

**Comment by MysticFoxDE** [comment]
Hi @OmerrGithubb,

it's easy, you just have to run the "W10ANDW11-NETWORK-TCP-BACKSUBOPTIMIZATION.ps1".

Why do you want to undo the optimizations?
Did you find a problem somewhere?

Best Regards from Germany
Alex

**Comment by calicokatsu** [comment]
I'm experiencing Download Ramp-down issues and massive ping spikes after activating this script.

**Comment by OmerrGithubb** [comment]
> Hi @OmerrGithubb,
> 
> it's easy, you just have to run the "W10ANDW11-NETWORK-TCP-BACKSUBOPTIMIZATION.ps1".
> 
> Why do you want to undo the optimizations? Did you find a problem somewhere?
> 
> Best Regards from Germany Alex

I haven't found any issues it didn't make any difference so I wanted to revert the changes. thank you dude!
