### ISSUE TITLE
Vorheriges Backup einbauen möglich?

### ISSUE THREAD

**Issue by MaxMcBurn** [MysticFoxDE/WINDOWS-OPTIMIZATIONS#3]
Hey ..  ich würde es begrüßen, wenn das Script zuvor ein Backup von den Einstellungen erstellt (oder macht es das?)

**Comment by MysticFoxDE** [comment]
Moin MaxMcBurn,

schau dir mal den folgenden Post an.

https://administrator.de/tutorial/wie-man-das-windows-10-und-11-tcp-handling-wieder-desuboptimieren-kann-5529700198.html#comment-5563266583

wäre deine Anfrage damit erledigt?

Gruss Alex

**Comment by MaxMcBurn** [comment]
Hi Alex .. ich kämpfe mich noch bei den Kommentaren durch .. danke mein Held ^^
