### ISSUE TITLE
Script limits transfer speeds from 10GbE down to 1GbE

### ISSUE THREAD

**Issue by fsaritome** [MysticFoxDE/WINDOWS-OPTIMIZATIONS#7]
Hi,

I know the script is meant to run on Windows 10/11, but I wanted to see what happens if I run it on a Server2019 Machine.
After running the script, the Server was capped to exactly 1Gbps transfer speed / 100MBps copy speed via LAN.
Transfer speeds previously were around 5Gbps.

System specs:
Virtual Windows 2019Box running on an ESXi cluster with latest patches using the VMXNET3 Adapter.
If you like me to run this script on our systems, I'd be delighted to do so.

**Comment by MysticFoxDE** [comment]
Hi Cheesecake99,
It is not without reason that I wrote that this script is not suitable for execution on a server.
But, with the following three lines, your problem should be solved again. 😉

Set-NetOffloadGlobalSetting -ReceiveSideScaling Enabled
Set-NetOffloadGlobalSetting -PacketCoalescingFilter Enabled
Get-Netadapter -Physical | Set-NetAdapterAdvancedProperty -RegistryKeyword "*RSS" -RegistryValue 1

For more Information about network performance with  Windows Server 2019/2022 on ESXi , please look here.
https://community.spiceworks.com/topic/post/9386778

Best Regards from Germany
Alex

**Comment by fsaritome** [comment]
Hi Alex,
well, you know admins, always on the hunt for more speed ;).
Thank you for the restorative commands, the server is copying with its regular speed again.
And I'm more than happy to try all the info you suggested in that spiceworks link.

Best Regards
Ferit
